### PR TITLE
Add support for hg.mozilla.org

### LINKED ISSUE #5: Add support for hg.mozilla.org
We need to implement something similar to DXR and Searchfox (the code is in dxr.js, searchfox.js, dxr-common.js), but for hg.mozilla.org.
Basically, we want to show a coverage overlay on top of the source files in hg.mozilla.org (e.g. on top of https://hg.mozilla.org/mozilla-central/file/tip/widget/gtk/nsWindow.cpp).

### PR DESCRIPTION
**Pull request by divyabaid16**
Fix #5 
@marco-c , please let me know the changes which need to be done.

### CODE REVIEW

**Review by marco-c — CHANGES_REQUESTED** [review]
I'm pretty sure this doesn't work. The structure of the hg.mozilla.org page is completely different than the structure of DXR or Searchfox.
For example, you are calling `getNavigationPanel` from dxr-common.js, which is looking for an element with ID `panel-content`, but there's no such element on a hg.mozilla.org page.

**Comment by divyabaid16** [comment]
@marco-c , how can I test this extension locally?

**Comment by marco-c** [comment]
You can open "about:debugging", then click on the button to load a temporary addon and select the manifest.json file in the repository directory.
Whenever you make changes to the addon, you can press "Reload" in the addon entry in about:debugging.

Another option is to use [web-ext](https://github.com/mozilla/web-ext), in particular the *run* command.

**Comment by divyabaid16** [comment]
@marco-c  I had added the extension locally by adding the unedited mainfest.json file, it was working for the Bugzilla site but not for [drx](https://dxr.mozilla.org/mozilla-central/source/tools/code-coverage/CodeCoverageHandler.cpp) and [searchfox](https://searchfox.org/mozilla-central/source/tools/code-coverage/CodeCoverageHandler.cpp). Since it was not working for both of these sites, I am unable to test it for hg.mozilla.org. Can you please tell me why is the local extension not working with dxr and searchfox if [this](https://addons.mozilla.org/en-US/firefox/addon/gecko-code-coverage/) is working ?

**Comment by marco-c** [comment]
Hey @divyabaid16, please reopen if you manage to make the extension work. Otherwise, there are other good first bugs in other repositories that you might work on that don't require building an extension.

**Pull request closed without merging**
