### PR TITLE
Removed all references for Bugzilla

### LINKED ISSUE #54: Remove Bugzilla support
Given that we upload coverage directly to Phabricator, Bugzilla support doesn't seem necessary anymore.

### PR DESCRIPTION
**Pull request by melvin2016**
Fixes #54 - all the references from .js and every other files regarding is removed.

### CODE REVIEW

**Comment by melvin2016** [comment]
i cant fix the eslint failing test.

**Comment by marco-c** [comment]
> i cant fix the eslint failing test.

Don't worry, they are pre-existing and not due to your patch.

**Comment by melvin2016** [comment]
Is this patch okay,?

**Review by marco-c — APPROVED** [review]
LGTM!
Please remove the .DS_Store from the patch though.

**Comment by melvin2016** [comment]
> Is this patch okay,?

Deleted !

**Comment by marco-c** [comment]
Thanks!

**Comment by marco-c** [comment]
If you want, you can do #51, which is pretty similar.

**Pull request merged**
