### PR TITLE
coverage information in the uplift request comments

### LINKED ISSUE #10: In Bugzilla, show coverage information in the uplift request comments
cc @sylvestre

### PR DESCRIPTION
**Pull request by divyabaid16**
Fix #10

### CODE REVIEW

**Review by marco-c — CHANGES_REQUESTED** [review]
You're duplicating a lot of the code, it shouldn't be necessary.
You can reuse the already existing code.

**Comment by marco-c** [comment]
Have you tested this? @divyabaid16

**Comment by divyabaid16** [comment]
There are some more changes to be made and I am working on it. Will soon update the status.

**Comment by divyabaid16** [comment]
I have added the code coverage element inside the uplift request comment at the end. But I am unable to add it between the specified string as I am using the same function for both the code coverage result. Can you plz suggest me what changes are needed to be made in so that the code coverage element gets inserted between the given string which is inside the HTML element if I know the starting index of the given string.

**Comment by marco-c** [comment]
@divyabaid16 you shouldn't use exactly the same function in the two cases. You should split **createCodeCoverage** in several parts and only use the parts you actually need.

**Comment by divyabaid16** [comment]
@marco-c , I have made some changes please review the code.

**Comment by marco-c** [comment]
The comment still applies:
> @divyabaid16 you shouldn't use exactly the same function in the two cases. You should split createCodeCoverage in several parts and only use the parts you actually need.

For example, you are retrieving the coverage data multiple times, while you would only need to load it once (since it's the same for the Details field and for the comments).

**Comment by divyabaid16** [comment]
When I split the code into two functions, the first one that calculates the code coverage information and the other one for creating the "Code Coverage" div elements I am not getting the desired result. I am getting code coverage of "details" section shifted completely towards the right but it is working fine with the comment section. Here is the screenshot for the same.
comment
details
Adding the code:
```const container = document.getElementById('module-details-content');
  const field_has_str = document.getElementById('field_label_cf_has_str');

  const bugzilla_modal_ui = !!container;
  const ab=createCodeCoverage(bugzilla_modal_ui);
  console.log("main value:"+ab);
  cc(bugzilla_modal_ui,container,field_has_str,ab);

   var uplift;
    var j=0, k=0;
    var element =  document.getElementById('ct-'+j);
    //var str = "[Has the fix been verified in Nightly?]";
    var str="I wonder if I can help out with this";
    while (k<50){

        var i;
        if(element.innerHTML.indexOf(str)>-1){
           var str_innerHtml = element.innerHTML;
           uplift=element;
           const bugzilla_modal_ui_uplift = !!element;
           cc(bugzilla_modal_ui_uplift,element,uplift,ab);
           break;
        }
        element =  document.getElementById('ct-'+j);
        j++;
        k++;
   }

Can you please help me out with this ?

**Comment by marco-c** [comment]
Hey @divyabaid16, maybe you should start with something simpler first to get more experienced.

**Comment by marco-c** [comment]
I'm going to do this myself, as some people are asking for this feature.

**Pull request closed without merging**
